In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [3]:
# lets get the first attribute of our array

x[0,]

1

In [5]:
# sixth attribute of our array

x[5,]

6

In [6]:
# Lets get every element until fourth

x[:4]

array([1, 2, 3, 4])

In [7]:
# To save an array

np.save('x', x)

In [8]:
# To load an array

np.load("x.npy")

array([1, 2, 3, 4, 5, 6])